load("@com_github_mihaibojin_bazel_java_rules//checkstyle:rules.bzl", "checkstyle")

checkstyle(
    name = "checkstyle",
    srcs = glob(["java/**/*.java"]),
    license_header = "//java/third_party/checkstyle:license-header.txt",
)
